server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root
  application:
    name: service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update